### PR TITLE
fixed error message for no events and fixed filter using search option

### PR DESCRIPTION
**Pull request by Ev1lGoldFish**
-fixed error handling for no events
-fixed search using filter option to not search based on userName

### CODE REVIEW

**Review by Samkit02 — APPROVED** [review]
Approved

**Review by Samkit02 — APPROVED** [review]

**Comment by Ev1lGoldFish** [comment]
Resolved conflicts

**Comment by Samkit02** [comment]
> Resolved conflicts

Some deployment checks are getting failed.

**Comment by Ev1lGoldFish** [comment]
[reverted changes to before resolving conflicts]

**Pull request merged**
